### ISSUE TITLE
Tugas1

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD3104#1]
<img width="490" alt="Screenshot 2024-10-07 at 8 07 01 PM" src="https://github.com/user-attachments/assets/fd512213-db75-4240-8c2e-68b3ee16bf80"> 

1.  Buatlah tree dan rule untuk mendeteksi adanya gangguan pada jaringan komputer menggunakan data di atas
2. Berapa persen besarnya error yang terjadi tanpa penyederhanaan (pruning) dan dengan penyederhanaan

Deadline: 14 Oktober 2024, 23:59

**Comment by RyanHakim24** [comment]
## Ryan Fadhilah Faizal Hakim - 2C2220007

https://github.com/RyanHakim24/2C2220007_Ryan_Tugas1_Machine_Learning

**Comment by riinndescartes** [comment]
Catherine V. Pang - 2C220008
[Tugas 1 Decision Tree Algoritma ID3 ](https://github.com/riinndescartes/Machine-Learning/blob/main/MK%20Machine%20Learning%20Tugas%20Pt(1)%20Decision%20Tree%20Algoritma%20ID3%20Catherine.pdf)

**Comment by tenideinarosa** [comment]
Teni Deinarosa Hermalia _2C2220005
![MachineLearning1_TeniDeinarosaH_2C2220005_05](https://github.com/user-attachments/assets/a447f0b0-bfc7-467c-a5cf-6e048b9360b5)

**Comment by tenideinarosa** [comment]
Teni Deinarosa Hermalia _2C2220005
[MachineLearning1_TeniDeinarosaH_2C2220005.PDF](https://github.com/user-attachments/files/17366121/MachineLearning1_TeniDeinarosaH_2C2220005.PDF)

**Comment by IndrNurSukmawati** [comment]
Indri Nur Sukmawati - 2C2220010

[Indri Nur Sukmawati_2C2220010_Tugas 1_Tree and Rule_Machine Learning.pdf](https://github.com/user-attachments/files/17366181/Indri.Nur.Sukmawati_2C2220010_Tugas.1_Tree.and.Rule_Machine.Learning.pdf)

**Comment by MulyatiEKaSaputri** [comment]
Mulyati Eka Saputri -2C22200099
[Mulyati Eka Saputri-2C2220009_Machine Learning(Decission Tree)-1.pdf](https://github.com/user-attachments/files/17366401/Mulyati.Eka.Saputri-2C2220009_Machine.Learning.Decission.Tree.-1.pdf)

**Comment by SilviNurinsan** [comment]
Silvi Nurinsan - 2C2220006
[Uploading SilviNurinsan_2C2220006_Tugas1 Machine Learning.pdf…]()

**Comment by SilviNurinsan** [comment]
Silvi Nurinsan - 2C2220006
[SilviNurinsan_2C2220006_Tugas1 Machine Learning.pdf](https://github.com/user-attachments/files/17366491/SilviNurinsan_2C2220006_Tugas1.Machine.Learning.pdf)

**Comment by cahyarahma** [comment]
Cahya Rahmawati | 2C2220011
https://drive.google.com/file/d/1GocdFPBt6bM2UNLFzbugYnTTmZyrMTl9/view?usp=drivesdk

**Comment by SagaraAndiLS** [comment]
Sagara Andi Ladzuardi Suwarsa
2C2220004

![Decision Tree Machine Learning Sagara Tugas 1.pdf](https://github.com/user-attachments/files/17367084/Decision.Tree.Machine.Learning.Sagara.Tugas.1.pdf)

**Comment by sevinurafni** [comment]
> Sagara Andi Ladzuardi Suwarsa 2C2220004
> 
> ![Decision Tree Machine Learning Sagara Tugas 1.pdf](https://github.com/user-attachments/files/17367084/Decision.Tree.Machine.Learning.Sagara.Tugas.1.pdf)

Sagara, di-pdf kan ya saya bingung liatnya

**Comment by SagaraAndiLS** [comment]
> > Sagara Andi Ladzuardi Suwarsa 2C2220004
> > 
> > ![Decision Tree Machine Learning Sagara Tugas 1.pdf](https://github.com/user-attachments/files/17367084/Decision.Tree.Machine.Learning.Sagara.Tugas.1.pdf)
> 
> Sagara, di-pdf kan ya saya bingung liatnya

Ijin mengirimkan lg Bu🙏🙏🙏
![Tugas 1 Decision Tree Sagara .pdf](https://github.com/user-attachments/files/17367282/Tugas.1.Decision.Tree.Sagara.pdf)

**Comment by ashafamultazam** [comment]
Ashafa Multazam - 2C2220012
[tugas 1 decision tree.pdf](https://github.com/user-attachments/files/17381480/tugas.1.decision.tree.pdf)
