### ISSUE TITLE
P1 Decision Tree

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD3104#2]
Kerjakan tugas untuk praktikum

https://colab.research.google.com/drive/1FnYot2VMaJUf9ooEUlsHA8FByL7RiJoq?usp=sharing
[diabetes_dataset.csv](https://github.com/user-attachments/files/17371905/diabetes_dataset.csv)

dikumpulkan pada akhir kelas praktikum dengan format file 
P1_NRP.pdf

**Comment by SagaraAndiLS** [comment]
Nama : Sagara Andi L S
NRP   : 2C2220004

[Tugas Decision Tree Sagara Andi L S.pdf](https://github.com/user-attachments/files/17373951/Tugas.Decision.Tree.Sagara.Andi.L.S.pdf)

**Comment by riinndescartes** [comment]
Catherine V. Pang - 2C2220008

`[Praktikum Pt(1) Decision Tree](https://github.com/riinndescartes/Machine-Learning/blob/main/1-praktikum-decision-tree-diabetes.pdf)`

**Comment by riinndescartes** [comment]
Catherine V . Pang - 2C2220008

[Praktikum Pt(1) Decision Tree](https://github.com/riinndescartes/Machine-Learning/blob/main/1-praktikum-decision-tree-diabetes.pdf)

**Comment by RyanHakim24** [comment]
## Ryan Fadhilah Faizal Hakim - 2C2220007

Link Praktikum 1 is [here](https://github.com/RyanHakim24/2C2220007_Ryan_Praktikum1_Machine_Learning)

**Comment by cahyarahma** [comment]
Nama : Cahya Rahmawati
NRP : 2C2220011
[Cahya Rahmawati_P1_2C2220011.pdf](https://github.com/user-attachments/files/17374052/Cahya.Rahmawati_P1_2C2220011.pdf)

**Comment by SilviNurinsan** [comment]
Silvi Nurinsan
2C2220006
[Silvi Nurinsan_P1_2C2220006_Machine Learning.pdf](https://github.com/user-attachments/files/17374127/Silvi.Nurinsan_P1_2C2220006_Machine.Learning.pdf)

**Comment by IndrNurSukmawati** [comment]
INDRI NUR SUKMAWATI - 2C2220010

[INDRI NUR SUKMAWATI_P1_2C2220010.pdf](https://github.com/user-attachments/files/17374152/INDRI.NUR.SUKMAWATI_P1_2C2220010.pdf)

**Comment by tenideinarosa** [comment]
TENI DEINAROSA HERMALIA
2C2220005
[P1_2C2220005_TENI DEINAROSA H.pdf](https://github.com/user-attachments/files/17374150/P1_2C2220005_TENI.DEINAROSA.H.pdf)

**Comment by MulyatiEKaSaputri** [comment]
Mulyati Eka Saputri
2C2220009
[Mulyati Eka Saputri_2C2220009_P1 DECISION TREE.pdf](https://github.com/user-attachments/files/17374163/Mulyati.Eka.Saputri_2C2220009_P1.DECISION.TREE.pdf)

**Comment by ashafamultazam** [comment]
Ashafa Multazam - 2C2220012
[lab decision tree.pdf](https://github.com/user-attachments/files/17381534/lab.decision.tree.pdf)

**Comment by betrandathariq** [comment]
Betrand Athariq Delpiero F 2C2220001
[BetrandAthariqDelpieroF_2C2220001_.DECISION.TREE.pdf](https://github.com/user-attachments/files/17405385/BetrandAthariqDelpieroF_2C2220001_.DECISION.TREE.pdf)
