### ISSUE TITLE
P2 Regression

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD3104#4]
Praktikum dikumpulkan pukul 14:40

https://colab.research.google.com/drive/18ALyVB4vCixej3qRkCuyHxIz9mkbAnfj?usp=sharing
https://colab.research.google.com/drive/17Ugt92hUxwEPLZvDQDIxkCtdTQ-Xnov0?usp=sharing
[bank-additional-full.csv](https://github.com/user-attachments/files/17467617/bank-additional-full.csv)
[df_train.csv](https://github.com/user-attachments/files/17467618/df_train.csv)
[df_test.csv](https://github.com/user-attachments/files/17467619/df_test.csv)

**Comment by SagaraAndiLS** [comment]
Nama: Sagara Andi L S
NRP : 2C2220004

[P-LinearRegression Sagara.pdf](https://github.com/user-attachments/files/17472132/P-LinearRegression.Sagara.pdf)
[P-LogisticRegression Sagara.pdf](https://github.com/user-attachments/files/17472133/P-LogisticRegression.Sagara.pdf)

**Comment by tenideinarosa** [comment]
TENI DEINAROSA HERMALIA
2C2220005
[P2_2C2220005_TENI DEINAROSA H.pdf](https://github.com/user-attachments/files/17472436/P2_2C2220005_TENI.DEINAROSA.H.pdf)

**Comment by IndrNurSukmawati** [comment]
INDRI NUR SUKMAWATI - 2C2220010
[INDRI NUR SUKMAWATI_2C2220010_P2_MACHIEN LEARNING.pdf](https://github.com/user-attachments/files/17476154/INDRI.NUR.SUKMAWATI_2C2220010_P2_MACHIEN.LEARNING.pdf)

**Comment by SilviNurinsan** [comment]
Silvi Nurinsan - 2C2220006
[SilviNurinsan_praktikum 2.pdf](https://github.com/user-attachments/files/17476301/SilviNurinsan_praktikum.2.pdf)

**Comment by cahyarahma** [comment]
Cahya Rahmawati | 2C2220011 |P2
https://drive.google.com/file/d/1KDGWQIvyfbMQnyXTxlEPlP0I-SwQ_ztH/view?usp=drivesdk

**Comment by ashafamultazam** [comment]
ASHAFA MULTAZAM 
2C2220012
https://drive.google.com/file/d/1jENFXn4ZLWzqasYI_2UgpfJjgPxuP-9V/view?usp=drivesdk

**Comment by MulyatiEKaSaputri** [comment]
Mulyati Eka Saputri 
2C2220009
[Mulyati Eka Saputri_2C2220009_P2.pdf](https://github.com/user-attachments/files/17478640/Mulyati.Eka.Saputri_2C2220009_P2.pdf)

**Comment by RyanHakim24** [comment]
## Ryan Fadhilah Faizal Hakim - 2C2220007

Link praktikum 2 is [here](https://github.com/RyanHakim24/2C2220007_Ryan_Praktikum2_Machine_Learning)

**Comment by riinndescartes** [comment]
Catherine V. Pang 2c222008

[Regresi Linear Berganda](https://github.com/riinndescartes/Machine-Learning/blob/main/Pt2_Praktikum_LinearRegression_Catherine.ipynb)
[Regresi Logistik](https://github.com/riinndescartes/Machine-Learning/blob/main/Pt2_Praktikum_LogisticRegression_Catherine.ipynb)

**Comment by betrandathariq** [comment]
Betrand Athariq Delpiero F 2C2220001

[BETRAND P2 Machine Learning.pdf](https://github.com/user-attachments/files/18337011/BETRAND.P2.Machine.Learning.pdf)
