### ISSUE TITLE
P3 SVM

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD3104#5]
https://colab.research.google.com/drive/1k8ey_DPM2aypK-S0RXw2zL-9EuoC9Xsb?usp=sharing

[bank-additional-full.csv](https://github.com/user-attachments/files/17550187/bank-additional-full.csv)

**Comment by SagaraAndiLS** [comment]
Nama : Sagara Andi L S
NRP   : 2C2220004
Link   : https://colab.research.google.com/drive/1DmGV09K4o7B285pnzEJt2B5Jb8CP00Fb#scrollTo=bVFsPc8Eb-9V

[SVM Sagara Andi L S.pdf](https://github.com/user-attachments/files/17552997/SVM.Sagara.Andi.L.S.pdf)

**Comment by cahyarahma** [comment]
Nama : Cahya Rahmawati
NRP : 2C2220011
https://colab.research.google.com/drive/1YVymKSF6bsPPUBtu7ArMfDmMl0xTOkq2?usp=sharing 
[Cahya Rahmawati _ 2C2220011 _ P3.pdf](https://github.com/user-attachments/files/17553221/Cahya.Rahmawati._.2C2220011._.P3.pdf)

**Comment by IndrNurSukmawati** [comment]
INDRI NUR SUKMAWATI - 2C2220010

LINK GOOGLE COLAB
https://colab.research.google.com/drive/18wdyzN3Cn-dSLUxAq7b4McSym5k3OV-h#scrollTo=bVFsPc8Eb-9V

[INDRI NUR SUKMAWATI_2C2220010_P3.pdf](https://github.com/user-attachments/files/17553291/INDRI.NUR.SUKMAWATI_2C2220010_P3.pdf)

**Comment by cahyarahma** [comment]
Nama : Cahya Rahmawati
NRP : 2C2220011
https://colab.research.google.com/drive/1YVymKSF6bsPPUBtu7ArMfDmMl0xTOkq2?usp=sharing  
[Cahya Rahmawati _ 2C2220011 _ P3.pdf](https://github.com/user-attachments/files/17553337/Cahya.Rahmawati._.2C2220011._.P3.pdf)

**Comment by MulyatiEKaSaputri** [comment]
Nama : Mulyati Eka Saputri
NRP : 2C2220009
https://colab.research.google.com/drive/1BwVaVv4fCF8tGD4OPEAPQ79gLIee7izR#scrollTo=2wOfKP55Fb_6
 
[Mulyati Eka Saputri_2C2220009_P3.pdf](https://github.com/user-attachments/files/17553366/Mulyati.Eka.Saputri_2C2220009_P3.pdf)

**Comment by riinndescartes** [comment]
[Catherine V. Pang - 2C2220008](https://github.com/riinndescartes/Machine-Learning/blob/main/Pt3_Praktikum_SVM_Catherine.ipynb)

**Comment by SilviNurinsan** [comment]
Nama : Silvi Nurinsan
Nrp : 2C2220006
https://colab.research.google.com/drive/1De9xt5AsAIBwuldYP6pqCWHOUISDAGXG?authuser=1#scrollTo=DKgKZsIvOABU
[Silvi Nurinsan_2C2220006_P3.pdf](https://github.com/user-attachments/files/17553410/Silvi.Nurinsan_2C2220006_P3.pdf)

**Comment by RyanHakim24** [comment]
## Ryan Fadhilah Faizal Hakim - 2C2220007

Here is the [link](https://github.com/RyanHakim24/2C2220007_Ryan_Praktikum3_Machine_Learning)

**Comment by ashafamultazam** [comment]
Ashafa Multazam - Lab Praktikum 3
https://colab.research.google.com/drive/1hmZxoOFynRcpjQdlIcqsqg_k0CfEtml7#scrollTo=6mt-FvuSdwRN

**Comment by tenideinarosa** [comment]
Teni Deinarosa Hermalia 
2C2220005
https://colab.research.google.com/drive/1zZnr2zHW2akRtu7C_WxieIIUxTlfJPSH?usp=sharing
[P3_TENI DEINAROSA H_2C2220005.pdf](https://github.com/user-attachments/files/17626061/P3_TENI.DEINAROSA.H_2C2220005.pdf)

**Comment by betrandathariq** [comment]
Betrand Athariq Delpiero F
2C2220001
https://colab.research.google.com/drive/11O8glK3JqrAEnXS5-po-VkxI5YZ1kJTX?usp=sharing
